### ISSUE TITLE
This is awesome! You should add a LICENSE

### ISSUE THREAD

**Issue by edaniels** [misprit7/computerraria#16]
Just so people can safely fork your code and contribute/derive.

**Comment by biotinker** [comment]
Ideally the same license would also be added to https://github.com/misprit7/WireHead

**Comment by 5donuts** [comment]
To expand on _why_ you should specify a license:
> Code without an explicit license is protected by copyright and is by default All Rights Reserved.
> [...]
> This means that you retain all rights to your source code and that nobody else may reproduce, distribute, or create derivative works from your work.

See: https://softwareengineering.stackexchange.com/a/276147/331405

Since you mentioned the code was "open source" in your video, I'm sure this isn't what you intended.
You should check out https://choosealicense.com/ and consider which license best suits your needs.

For what it's worth, many Rust developers dual-license their code under MIT and APACHE-2.0 to mirror the official Rust licensing stance (see: https://www.rust-lang.org/policies/licenses).
